CREATE TABLE PETINF (
 PETID                 int NOT NULL,
 PETNAME               VARCHAR(14),
 PETTYPE               VARCHAR(13),
 PETAGE                 int NOT NULL,
PETOWNER		VARCHAR(14),


INSERT INTO PETINF VALUES (1,'DOG','MALE',13,'SOWMYA');
INSERT INTO PETINF VALUES (2,'RABBIT','MALE',16,'HARSHINI');
INSERT INTO PETINF VALUES (3,'CAT','FEMALE',17,'SRIKANTH');
INSERT INTO PETINF VALUES (4,'SANKE','MALE',31,'KESHAVA');
INSERT INTO PETINF VALUES (5,'RAT','MALE',18,'HARSHITHA');
INSERT INTO PETINF VALUES (6,'PARROT','FEMALE',25,'THANUSRI');
