 CREATE TABLE PETDETAILS (
 PETID                 int NOT NULL,
 PETNAME               VARCHAR(14),
 PETTYPE               VARCHAR(13),
 PETAGE                 int NOT NULL,
PETOWNER		VARCHAR(14),
CONSTRAINT PETINF_PRIMARY_KEY PRIMARY KEY (PETID));

INSERT INTO PETDETAILS VALUES (1,'DOG','MALE',13,'SOWMYA');
INSERT INTO PETDETAILS VALUES (2,'RABBIT','MALE',16,'SRIKANTH');
INSERT INTO PETDETAILS VALUES (3,'CAT','FEMALE',17,'KESHAVA');
INSERT INTO PETDETAILS VALUES (4,'SANKE','MALE',31,'HARSHINI');
INSERT INTO PETDETAILS VALUES (5,'RAT','MALE',18,'HARSHITHA');
INSERT INTO PETDETAILS VALUES (6,'PARROT','FEMALE',25,'THANUSRI');

SELECT *FROM PETDETAILS;
