SELECT ENAME ,DNAME FROM DEPT D LEFT OUTER JOIN EMP E ON (E.DEPTNO = D.DEPTNO);
SELECT ENAME ,DNAME FROM DEPT D RIGHT OUTER JOIN EMP E ON (E.DEPTNO = D.DEPTNO);
SELECT ENAME ,DNAME FROM DEPT D FULL OUTER JOIN EMP E ON (E.DEPTNO = D.DEPTNO);
SELECT ENAME ,DNAME FROM DEPT D FULL OUTER JOIN EMP E ON (E.DEPTNO = D.DEPTNO)
WHERE COMM IS NULL;
SELECT JOB,DNAME,MIN(SAL) FROM DEPT D FULL OUTER JOIN EMP E ON (E.DEPTNO = D.DEPTNO)
WHERE COMM IS NULL
GROUP BY D.DNAME,JOB
HAVING MIN(SAL)<1500
ORDER BY MIN(SAL);
SELECT E.ENAME,D.DNAME FROM EMP E CROSS JOIN DEPT D;